const Sequelize = require('sequelize');
const banco = require('./../../banco');

const escalar = banco.define('ESCALAS', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  TELA: Sequelize.STRING,
  S1_DATA: Sequelize.STRING,
  S1_DATA: Sequelize.STRING,
  S1_DATA: Sequelize.STRING,
  S1_DATA: Sequelize.STRING,
  S1_MINISTRO: Sequelize.STRING,
  S1_VIOLAO: Sequelize.STRING,
  S1_BAIXO: Sequelize.STRING,
  S1_TECLADO: Sequelize.STRING,
  S1_BATERIA: Sequelize.STRING,
  S1_GUITARRA: Sequelize.STRING,
  S1_BACK_1: Sequelize.STRING,
  S1_BACK_2: Sequelize.STRING,
  S1_BACK_3: Sequelize.STRING,
  S1_MIDIA: Sequelize.STRING,
  S1_SOM: Sequelize.STRING,
  S1_DEVOCIONAL: Sequelize.STRING,
  S2_DATA: Sequelize.STRING,
  S2_DATA: Sequelize.STRING,
  S2_DATA: Sequelize.STRING,
  S2_DATA: Sequelize.STRING,
  S2_MINISTRO: Sequelize.STRING,
  S2_VIOLAO: Sequelize.STRING,
  S2_BAIXO: Sequelize.STRING,
  S2_TECLADO: Sequelize.STRING,
  S2_BATERIA: Sequelize.STRING,
  S2_GUITARRA: Sequelize.STRING,
  S2_BACK_1: Sequelize.STRING,
  S2_BACK_2: Sequelize.STRING,
  S2_BACK_3: Sequelize.STRING,
  S2_MIDIA: Sequelize.STRING,
  S2_SOM: Sequelize.STRING,
  S2_DEVOCIONAL: Sequelize.STRING,
  S3_DATA: Sequelize.STRING,
  S3_DATA: Sequelize.STRING,
  S3_DATA: Sequelize.STRING,
  S3_DATA: Sequelize.STRING,
  S3_MINISTRO: Sequelize.STRING,
  S3_VIOLAO: Sequelize.STRING,
  S3_BAIXO: Sequelize.STRING,
  S3_TECLADO: Sequelize.STRING,
  S3_BATERIA: Sequelize.STRING,
  S3_GUITARRA: Sequelize.STRING,
  S3_BACK_1: Sequelize.STRING,
  S3_BACK_2: Sequelize.STRING,
  S3_BACK_3: Sequelize.STRING,
  S3_MIDIA: Sequelize.STRING,
  S3_SOM: Sequelize.STRING,
  S3_DEVOCIONAL: Sequelize.STRING,
  S4_DATA: Sequelize.STRING,
  S4_DATA: Sequelize.STRING,
  S4_DATA: Sequelize.STRING,
  S4_DATA: Sequelize.STRING,
  S4_MINISTRO: Sequelize.STRING,
  S4_VIOLAO: Sequelize.STRING,
  S4_BAIXO: Sequelize.STRING,
  S4_TECLADO: Sequelize.STRING,
  S4_BATERIA: Sequelize.STRING,
  S4_GUITARRA: Sequelize.STRING,
  S4_BACK_1: Sequelize.STRING,
  S4_BACK_2: Sequelize.STRING,
  S4_BACK_3: Sequelize.STRING,
  S4_MIDIA: Sequelize.STRING,
  S4_SOM: Sequelize.STRING,
  S4_DEVOCIONAL: Sequelize.STRING,
  S5_DATA: Sequelize.STRING,
  S5_DATA: Sequelize.STRING,
  S5_DATA: Sequelize.STRING,
  S5_DATA: Sequelize.STRING,
  S5_MINISTRO: Sequelize.STRING,
  S5_VIOLAO: Sequelize.STRING,
  S5_BAIXO: Sequelize.STRING,
  S5_TECLADO: Sequelize.STRING,
  S5_BATERIA: Sequelize.STRING,
  S5_GUITARRA: Sequelize.STRING,
  S5_BACK_1: Sequelize.STRING,
  S5_BACK_2: Sequelize.STRING,
  S5_BACK_3: Sequelize.STRING,
  S5_MIDIA: Sequelize.STRING,
  S5_SOM: Sequelize.STRING,
  S5_DEVOCIONAL: Sequelize.STRING,
},
{
  tableName: 'ESCALAS',
  timestamps: false,
}
);

module.exports = escalar;